version: '3'

services:
    web:
        image: nginx:1.16.0
        container_name: nginx
        restart: always
        volumes:
            - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./server/ssl:/etc/ssl
            - ./www:/var/www/html
        ports:
            - "80:80"
            - "443:443"     
        links:
            - php
            - mysql
            
    php:
        build: ./server
        image: php-ci-cd
        container_name: php-ci-cd
        restart: always
        volumes:
            - ./www:/var/www/html
            - ./server/php/php.ini:/usr/local/etc/php/conf.d/php.ini
   
    mysql:
        image: mysql:5.7
        container_name: mysql       
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root    
        volumes:
            - ./db:/var/lib/mysql
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - "8000:80"
        environment:
            MYSQL_ROOT_PASSWORD: root
        links: 
            - mysql:db