version: '3'

services:
    www:
        build: .
        image: php-ci-cd
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db

    db:
        image: mysql:8.0    
        ports: 
            - "3305:3306"
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD="true"
            - MYSQL_DATABASE=php-test
        volumes:
            - ./db:/var/lib/mysql
      
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8000:80
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        links: 
            - db:db