version: '3'

services:
    www:
        build: .
        image: php-ci-cd
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db
        networks:
            - default

    db:
        image: mysql:8.0    
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD = "true"
            - MYSQL_USER: admin
            - MYSQL_PASSWORD: admin
            - MYSQL_DATABASE=php-ci-cd
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - default
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8000:80
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        links: 
            - db:db
        networks:
            - default