version: '3'

services:
    www:
        build: 
            context: ./server
        image: php-ci-cd
        container_name: php-ci-cd
        ports:
            - "80:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db

    db:
        image: mysql:8.0
        container_name: mysql       
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_DATABASE: php-ci-cd
        volumes:
            - ./db:/var/lib/mysql
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8000:80
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        links: 
            - db:db